/*
 * BalsameeAPIs.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json.Converters;
using BalsameeAPIs.Standard;
using BalsameeAPIs.Standard.Utilities;
using BalsameeAPIs.Standard.Http.Request;
using BalsameeAPIs.Standard.Http.Response;
using BalsameeAPIs.Standard.Http.Client;
using BalsameeAPIs.Standard.Exceptions;

namespace BalsameeAPIs.Standard.Controllers
{
    public partial class ReservationRequestsController: BaseController
    {
        #region Singleton Pattern

        //private static variables for the singleton pattern
        private static object syncObject = new object();
        private static ReservationRequestsController instance = null;

        /// <summary>
        /// Singleton pattern implementation
        /// </summary>
        internal static ReservationRequestsController Instance
        {
            get
            {
                lock (syncObject)
                {
                    if (null == instance)
                    {
                        instance = new ReservationRequestsController();
                    }
                }
                return instance;
            }
        }

        #endregion Singleton Pattern

        /// <summary>
        ///     Create new reservation request
        ///     
        ///   URL: /reservation_requests
        ///   Method: POST
        ///   @param doctor_id
        ///   @param address
        ///   @param address_details
        ///   @param mobile_number
        ///   @param country_code
        ///   @param patient_latitude
        ///   @param patient_longitude
        ///   @param country_code] mobile country code
        ///   @header [String] X-Authentication-Token
        ///   @header [String] X-Session-Id
        ///   @return [JsonArray]  errors  ( code: 422 )
        /// </summary>
        /// <param name="xSessionId">Required parameter: Example: </param>
        /// <param name="xAuthenticationToken">Required parameter: Example: </param>
        /// <param name="doctorId">Required parameter: Example: </param>
        /// <param name="address">Required parameter: Example: </param>
        /// <param name="addressDetails">Required parameter: Example: </param>
        /// <param name="mobileNumber">Required parameter: Example: </param>
        /// <param name="patientLatitude">Required parameter: Example: </param>
        /// <param name="patientLongitude">Required parameter: Example: </param>
        /// <return>Returns the void response from the API call</return>
        public void CreateApiV5ReservationRequestsPost(
                string xSessionId,
                string xAuthenticationToken,
                string doctorId,
                string address,
                string addressDetails,
                string mobileNumber,
                string patientLatitude,
                string patientLongitude)
        {
            Task t = CreateApiV5ReservationRequestsPostAsync(xSessionId, xAuthenticationToken, doctorId, address, addressDetails, mobileNumber, patientLatitude, patientLongitude);
            APIHelper.RunTaskSynchronously(t);
        }

        /// <summary>
        ///     Create new reservation request
        ///     
        ///   URL: /reservation_requests
        ///   Method: POST
        ///   @param doctor_id
        ///   @param address
        ///   @param address_details
        ///   @param mobile_number
        ///   @param country_code
        ///   @param patient_latitude
        ///   @param patient_longitude
        ///   @param country_code] mobile country code
        ///   @header [String] X-Authentication-Token
        ///   @header [String] X-Session-Id
        ///   @return [JsonArray]  errors  ( code: 422 )
        /// </summary>
        /// <param name="xSessionId">Required parameter: Example: </param>
        /// <param name="xAuthenticationToken">Required parameter: Example: </param>
        /// <param name="doctorId">Required parameter: Example: </param>
        /// <param name="address">Required parameter: Example: </param>
        /// <param name="addressDetails">Required parameter: Example: </param>
        /// <param name="mobileNumber">Required parameter: Example: </param>
        /// <param name="patientLatitude">Required parameter: Example: </param>
        /// <param name="patientLongitude">Required parameter: Example: </param>
        /// <return>Returns the void response from the API call</return>
        public async Task CreateApiV5ReservationRequestsPostAsync(
                string xSessionId,
                string xAuthenticationToken,
                string doctorId,
                string address,
                string addressDetails,
                string mobileNumber,
                string patientLatitude,
                string patientLongitude)
        {
            //the base uri for api requests
            string _baseUri = Configuration.GetBaseURI();

            //prepare query string for API call
            StringBuilder _queryBuilder = new StringBuilder(_baseUri);
            _queryBuilder.Append("/reservation_requests");


            //validate and preprocess url
            string _queryUrl = APIHelper.CleanUrl(_queryBuilder);

            //append request with appropriate headers and parameters
            var _headers = new Dictionary<string,string>()
            {
                { "user-agent", "APIMATIC 2.0" },
                { "X-Session-Id", xSessionId },
                { "X-Authentication-Token", xAuthenticationToken }
            };

            //append form/field parameters
            var _fields = new List<KeyValuePair<string, Object>>()
            {
                new KeyValuePair<string, object>( "doctor_id", doctorId ),
                new KeyValuePair<string, object>( "address", address ),
                new KeyValuePair<string, object>( "address_details", addressDetails ),
                new KeyValuePair<string, object>( "mobile_number", mobileNumber ),
                new KeyValuePair<string, object>( "patient_latitude", patientLatitude ),
                new KeyValuePair<string, object>( "patient_longitude", patientLongitude )
            };
            //remove null parameters
            _fields = _fields.Where(kvp => kvp.Value != null).ToList();

            //prepare the API call request to fetch the response
            HttpRequest _request = ClientInstance.Post(_queryUrl, _headers, _fields);

            //invoke request and get response
            HttpStringResponse _response = (HttpStringResponse) await ClientInstance.ExecuteAsStringAsync(_request).ConfigureAwait(false);
            HttpContext _context = new HttpContext(_request,_response);
            //handle errors defined at the API level
            base.ValidateResponse(_response, _context);

        }

        /// <summary>
        /// TODO: Add Description
        /// </summary>
        /// <param name="xAuthenticationToken">Required parameter: Example: </param>
        /// <param name="xSessionId">Required parameter: Example: </param>
        /// <param name="ratingStars">Required parameter: Example: </param>
        /// <param name="ratingReview">Required parameter: Example: </param>
        /// <return>Returns the void response from the API call</return>
        public void CreateApiV5ReservationRequests2685RatingsPost(
                string xAuthenticationToken,
                string xSessionId,
                string ratingStars,
                string ratingReview)
        {
            Task t = CreateApiV5ReservationRequests2685RatingsPostAsync(xAuthenticationToken, xSessionId, ratingStars, ratingReview);
            APIHelper.RunTaskSynchronously(t);
        }

        /// <summary>
        /// TODO: Add Description
        /// </summary>
        /// <param name="xAuthenticationToken">Required parameter: Example: </param>
        /// <param name="xSessionId">Required parameter: Example: </param>
        /// <param name="ratingStars">Required parameter: Example: </param>
        /// <param name="ratingReview">Required parameter: Example: </param>
        /// <return>Returns the void response from the API call</return>
        public async Task CreateApiV5ReservationRequests2685RatingsPostAsync(
                string xAuthenticationToken,
                string xSessionId,
                string ratingStars,
                string ratingReview)
        {
            //the base uri for api requests
            string _baseUri = Configuration.GetBaseURI();

            //prepare query string for API call
            StringBuilder _queryBuilder = new StringBuilder(_baseUri);
            _queryBuilder.Append("/reservation_requests/2685/ratings");


            //validate and preprocess url
            string _queryUrl = APIHelper.CleanUrl(_queryBuilder);

            //append request with appropriate headers and parameters
            var _headers = new Dictionary<string,string>()
            {
                { "user-agent", "APIMATIC 2.0" },
                { "X-Authentication_Token", xAuthenticationToken },
                { "X-Session_Id", xSessionId }
            };

            //append form/field parameters
            var _fields = new List<KeyValuePair<string, Object>>()
            {
                new KeyValuePair<string, object>( "rating[stars]", ratingStars ),
                new KeyValuePair<string, object>( "rating[review]", ratingReview )
            };
            //remove null parameters
            _fields = _fields.Where(kvp => kvp.Value != null).ToList();

            //prepare the API call request to fetch the response
            HttpRequest _request = ClientInstance.Post(_queryUrl, _headers, _fields);

            //invoke request and get response
            HttpStringResponse _response = (HttpStringResponse) await ClientInstance.ExecuteAsStringAsync(_request).ConfigureAwait(false);
            HttpContext _context = new HttpContext(_request,_response);
            //handle errors defined at the API level
            base.ValidateResponse(_response, _context);

        }

        /// <summary>
        /// Doctor reject resesrvation request
        /// </summary>
        /// <param name="xAuthenticationToken">Required parameter: Example: </param>
        /// <param name="xSessionId">Required parameter: Example: </param>
        /// <param name="currentStatus">Required parameter: Example: </param>
        /// <return>Returns the void response from the API call</return>
        public void UpdateApiV5ReservationRequests4142Put(string xAuthenticationToken, string xSessionId, string currentStatus)
        {
            Task t = UpdateApiV5ReservationRequests4142PutAsync(xAuthenticationToken, xSessionId, currentStatus);
            APIHelper.RunTaskSynchronously(t);
        }

        /// <summary>
        /// Doctor reject resesrvation request
        /// </summary>
        /// <param name="xAuthenticationToken">Required parameter: Example: </param>
        /// <param name="xSessionId">Required parameter: Example: </param>
        /// <param name="currentStatus">Required parameter: Example: </param>
        /// <return>Returns the void response from the API call</return>
        public async Task UpdateApiV5ReservationRequests4142PutAsync(string xAuthenticationToken, string xSessionId, string currentStatus)
        {
            //the base uri for api requests
            string _baseUri = Configuration.GetBaseURI();

            //prepare query string for API call
            StringBuilder _queryBuilder = new StringBuilder(_baseUri);
            _queryBuilder.Append("/reservation_requests/4142");


            //validate and preprocess url
            string _queryUrl = APIHelper.CleanUrl(_queryBuilder);

            //append request with appropriate headers and parameters
            var _headers = new Dictionary<string,string>()
            {
                { "user-agent", "APIMATIC 2.0" },
                { "X-Authentication-Token", xAuthenticationToken },
                { "X-Session-Id", xSessionId }
            };

            //append form/field parameters
            var _fields = new List<KeyValuePair<string, Object>>()
            {
                new KeyValuePair<string, object>( "current_status", currentStatus )
            };
            //remove null parameters
            _fields = _fields.Where(kvp => kvp.Value != null).ToList();

            //prepare the API call request to fetch the response
            HttpRequest _request = ClientInstance.Put(_queryUrl, _headers, _fields);

            //invoke request and get response
            HttpStringResponse _response = (HttpStringResponse) await ClientInstance.ExecuteAsStringAsync(_request).ConfigureAwait(false);
            HttpContext _context = new HttpContext(_request,_response);
            //handle errors defined at the API level
            base.ValidateResponse(_response, _context);

        }

        /// <summary>
        /// TODO: Add Description
        /// </summary>
        /// <param name="xSessionId">Required parameter: Example: </param>
        /// <param name="xAuthenticationToken">Required parameter: Example: </param>
        /// <param name="promoCode">Required parameter: Example: </param>
        /// <return>Returns the void response from the API call</return>
        public void CreateApiV5ReservationRequestsCheckValidityCodePost(string xSessionId, string xAuthenticationToken, string promoCode)
        {
            Task t = CreateApiV5ReservationRequestsCheckValidityCodePostAsync(xSessionId, xAuthenticationToken, promoCode);
            APIHelper.RunTaskSynchronously(t);
        }

        /// <summary>
        /// TODO: Add Description
        /// </summary>
        /// <param name="xSessionId">Required parameter: Example: </param>
        /// <param name="xAuthenticationToken">Required parameter: Example: </param>
        /// <param name="promoCode">Required parameter: Example: </param>
        /// <return>Returns the void response from the API call</return>
        public async Task CreateApiV5ReservationRequestsCheckValidityCodePostAsync(string xSessionId, string xAuthenticationToken, string promoCode)
        {
            //the base uri for api requests
            string _baseUri = Configuration.GetBaseURI();

            //prepare query string for API call
            StringBuilder _queryBuilder = new StringBuilder(_baseUri);
            _queryBuilder.Append("/reservation_requests/check_validity_code");


            //validate and preprocess url
            string _queryUrl = APIHelper.CleanUrl(_queryBuilder);

            //append request with appropriate headers and parameters
            var _headers = new Dictionary<string,string>()
            {
                { "user-agent", "APIMATIC 2.0" },
                { "X-session-id", xSessionId },
                { "X-authentication-token", xAuthenticationToken }
            };

            //append form/field parameters
            var _fields = new List<KeyValuePair<string, Object>>()
            {
                new KeyValuePair<string, object>( "promo_code", promoCode )
            };
            //remove null parameters
            _fields = _fields.Where(kvp => kvp.Value != null).ToList();

            //prepare the API call request to fetch the response
            HttpRequest _request = ClientInstance.Post(_queryUrl, _headers, _fields);

            //invoke request and get response
            HttpStringResponse _response = (HttpStringResponse) await ClientInstance.ExecuteAsStringAsync(_request).ConfigureAwait(false);
            HttpContext _context = new HttpContext(_request,_response);
            //handle errors defined at the API level
            base.ValidateResponse(_response, _context);

        }

        /// <summary>
        /// TODO: Add Description
        /// </summary>
        /// <param name="xAuthenticationToken">Required parameter: Example: </param>
        /// <param name="xSessionId">Required parameter: Example: </param>
        /// <param name="caseInfo">Required parameter: Example: </param>
        /// <return>Returns the void response from the API call</return>
        public void UpdateApiV5ReservationRequests2668AddCaseInfoPatch(string xAuthenticationToken, string xSessionId, string caseInfo)
        {
            Task t = UpdateApiV5ReservationRequests2668AddCaseInfoPatchAsync(xAuthenticationToken, xSessionId, caseInfo);
            APIHelper.RunTaskSynchronously(t);
        }

        /// <summary>
        /// TODO: Add Description
        /// </summary>
        /// <param name="xAuthenticationToken">Required parameter: Example: </param>
        /// <param name="xSessionId">Required parameter: Example: </param>
        /// <param name="caseInfo">Required parameter: Example: </param>
        /// <return>Returns the void response from the API call</return>
        public async Task UpdateApiV5ReservationRequests2668AddCaseInfoPatchAsync(string xAuthenticationToken, string xSessionId, string caseInfo)
        {
            //the base uri for api requests
            string _baseUri = Configuration.GetBaseURI();

            //prepare query string for API call
            StringBuilder _queryBuilder = new StringBuilder(_baseUri);
            _queryBuilder.Append("/reservation_requests/2668/add_case_info");


            //validate and preprocess url
            string _queryUrl = APIHelper.CleanUrl(_queryBuilder);

            //append request with appropriate headers and parameters
            var _headers = new Dictionary<string,string>()
            {
                { "user-agent", "APIMATIC 2.0" },
                { "X-Authentication-Token", xAuthenticationToken },
                { "X-Session-Id", xSessionId }
            };

            //append form/field parameters
            var _fields = new List<KeyValuePair<string, Object>>()
            {
                new KeyValuePair<string, object>( "case_info", caseInfo )
            };
            //remove null parameters
            _fields = _fields.Where(kvp => kvp.Value != null).ToList();

            //prepare the API call request to fetch the response
            HttpRequest _request = ClientInstance.Patch(_queryUrl, _headers, _fields);

            //invoke request and get response
            HttpStringResponse _response = (HttpStringResponse) await ClientInstance.ExecuteAsStringAsync(_request).ConfigureAwait(false);
            HttpContext _context = new HttpContext(_request,_response);
            //handle errors defined at the API level
            base.ValidateResponse(_response, _context);

        }

        /// <summary>
        ///     Create new reservation request
        ///     
        ///   URL: /reservation_requests
        ///   Method: POST
        ///   @param doctor_id
        ///   @param address
        ///   @param address_details
        ///   @param mobile_number
        ///   @param country_code
        ///   @param patient_latitude
        ///   @param patient_longitude
        ///   @param country_code] mobile country code
        ///   @header [String] X-Authentication-Token
        ///   @header [String] X-Session-Id
        ///   @return [JsonArray]  errors  ( code: 422 )
        /// </summary>
        /// <param name="xSessionId">Required parameter: Example: </param>
        /// <param name="xAuthenticationToken">Required parameter: Example: </param>
        /// <return>Returns the void response from the API call</return>
        public void GetApiV5ReservationRequests2678Get(string xSessionId, string xAuthenticationToken)
        {
            Task t = GetApiV5ReservationRequests2678GetAsync(xSessionId, xAuthenticationToken);
            APIHelper.RunTaskSynchronously(t);
        }

        /// <summary>
        ///     Create new reservation request
        ///     
        ///   URL: /reservation_requests
        ///   Method: POST
        ///   @param doctor_id
        ///   @param address
        ///   @param address_details
        ///   @param mobile_number
        ///   @param country_code
        ///   @param patient_latitude
        ///   @param patient_longitude
        ///   @param country_code] mobile country code
        ///   @header [String] X-Authentication-Token
        ///   @header [String] X-Session-Id
        ///   @return [JsonArray]  errors  ( code: 422 )
        /// </summary>
        /// <param name="xSessionId">Required parameter: Example: </param>
        /// <param name="xAuthenticationToken">Required parameter: Example: </param>
        /// <return>Returns the void response from the API call</return>
        public async Task GetApiV5ReservationRequests2678GetAsync(string xSessionId, string xAuthenticationToken)
        {
            //the base uri for api requests
            string _baseUri = Configuration.GetBaseURI();

            //prepare query string for API call
            StringBuilder _queryBuilder = new StringBuilder(_baseUri);
            _queryBuilder.Append("/reservation_requests/2678");


            //validate and preprocess url
            string _queryUrl = APIHelper.CleanUrl(_queryBuilder);

            //append request with appropriate headers and parameters
            var _headers = new Dictionary<string,string>()
            {
                { "user-agent", "APIMATIC 2.0" },
                { "X-Session-Id", xSessionId },
                { "X-Authentication-Token", xAuthenticationToken }
            };

            //prepare the API call request to fetch the response
            HttpRequest _request = ClientInstance.Get(_queryUrl,_headers);

            //invoke request and get response
            HttpStringResponse _response = (HttpStringResponse) await ClientInstance.ExecuteAsStringAsync(_request).ConfigureAwait(false);
            HttpContext _context = new HttpContext(_request,_response);
            //handle errors defined at the API level
            base.ValidateResponse(_response, _context);

        }

        /// <summary>
        /// TODO: Add Description
        /// </summary>
        /// <param name="xAuthenticationToken">Required parameter: Example: </param>
        /// <param name="xSessionId">Required parameter: Example: </param>
        /// <return>Returns the void response from the API call</return>
        public void GetApiV5ReservationRequests2686ShowCaseInfoGet(string xAuthenticationToken, string xSessionId)
        {
            Task t = GetApiV5ReservationRequests2686ShowCaseInfoGetAsync(xAuthenticationToken, xSessionId);
            APIHelper.RunTaskSynchronously(t);
        }

        /// <summary>
        /// TODO: Add Description
        /// </summary>
        /// <param name="xAuthenticationToken">Required parameter: Example: </param>
        /// <param name="xSessionId">Required parameter: Example: </param>
        /// <return>Returns the void response from the API call</return>
        public async Task GetApiV5ReservationRequests2686ShowCaseInfoGetAsync(string xAuthenticationToken, string xSessionId)
        {
            //the base uri for api requests
            string _baseUri = Configuration.GetBaseURI();

            //prepare query string for API call
            StringBuilder _queryBuilder = new StringBuilder(_baseUri);
            _queryBuilder.Append("/reservation_requests/2686/show_case_info");


            //validate and preprocess url
            string _queryUrl = APIHelper.CleanUrl(_queryBuilder);

            //append request with appropriate headers and parameters
            var _headers = new Dictionary<string,string>()
            {
                { "user-agent", "APIMATIC 2.0" },
                { "X-Authentication-Token", xAuthenticationToken },
                { "X-Session-Id", xSessionId }
            };

            //prepare the API call request to fetch the response
            HttpRequest _request = ClientInstance.Get(_queryUrl,_headers);

            //invoke request and get response
            HttpStringResponse _response = (HttpStringResponse) await ClientInstance.ExecuteAsStringAsync(_request).ConfigureAwait(false);
            HttpContext _context = new HttpContext(_request,_response);
            //handle errors defined at the API level
            base.ValidateResponse(_response, _context);

        }

        /// <summary>
        /// TODO: Add Description
        /// </summary>
        /// <param name="xSessionId">Required parameter: Example: </param>
        /// <param name="xAuthenticationToken">Required parameter: Example: </param>
        /// <return>Returns the void response from the API call</return>
        public void GetApiV5ReservationRequestsGet(string xSessionId, string xAuthenticationToken)
        {
            Task t = GetApiV5ReservationRequestsGetAsync(xSessionId, xAuthenticationToken);
            APIHelper.RunTaskSynchronously(t);
        }

        /// <summary>
        /// TODO: Add Description
        /// </summary>
        /// <param name="xSessionId">Required parameter: Example: </param>
        /// <param name="xAuthenticationToken">Required parameter: Example: </param>
        /// <return>Returns the void response from the API call</return>
        public async Task GetApiV5ReservationRequestsGetAsync(string xSessionId, string xAuthenticationToken)
        {
            //the base uri for api requests
            string _baseUri = Configuration.GetBaseURI();

            //prepare query string for API call
            StringBuilder _queryBuilder = new StringBuilder(_baseUri);
            _queryBuilder.Append("/reservation_requests");


            //validate and preprocess url
            string _queryUrl = APIHelper.CleanUrl(_queryBuilder);

            //append request with appropriate headers and parameters
            var _headers = new Dictionary<string,string>()
            {
                { "user-agent", "APIMATIC 2.0" },
                { "X-Session-Id", xSessionId },
                { "X-Authentication-Token", xAuthenticationToken }
            };

            //prepare the API call request to fetch the response
            HttpRequest _request = ClientInstance.Get(_queryUrl,_headers);

            //invoke request and get response
            HttpStringResponse _response = (HttpStringResponse) await ClientInstance.ExecuteAsStringAsync(_request).ConfigureAwait(false);
            HttpContext _context = new HttpContext(_request,_response);
            //handle errors defined at the API level
            base.ValidateResponse(_response, _context);

        }

    }
} 