/*
 * BalsameeAPIs.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using BalsameeAPIs.Standard.Controllers;
using BalsameeAPIs.Standard.Http.Client;
using BalsameeAPIs.Standard.Utilities;

namespace BalsameeAPIs.Standard
{
    public partial class BalsameeAPIsClient
    {

        /// <summary>
        /// Singleton access to NewsTags controller
        /// </summary>
        public NewsTagsController NewsTags
        {
            get
            {
                return NewsTagsController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to StaticPages controller
        /// </summary>
        public StaticPagesController StaticPages
        {
            get
            {
                return StaticPagesController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to General controller
        /// </summary>
        public GeneralController General
        {
            get
            {
                return GeneralController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Misc controller
        /// </summary>
        public MiscController Misc
        {
            get
            {
                return MiscController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to MiniPmr controller
        /// </summary>
        public MiniPmrController MiniPmr
        {
            get
            {
                return MiniPmrController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to ListRadiologyRequestGroups controller
        /// </summary>
        public ListRadiologyRequestGroupsController ListRadiologyRequestGroups
        {
            get
            {
                return ListRadiologyRequestGroupsController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to RadiologyRequestImageGroup controller
        /// </summary>
        public RadiologyRequestImageGroupController RadiologyRequestImageGroup
        {
            get
            {
                return RadiologyRequestImageGroupController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Prescriptions controller
        /// </summary>
        public PrescriptionsController Prescriptions
        {
            get
            {
                return PrescriptionsController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to LabRequestGroups controller
        /// </summary>
        public LabRequestGroupsController LabRequestGroups
        {
            get
            {
                return LabRequestGroupsController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to PrescriptionGroups controller
        /// </summary>
        public PrescriptionGroupsController PrescriptionGroups
        {
            get
            {
                return PrescriptionGroupsController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to LabRequestImagesGroup controller
        /// </summary>
        public LabRequestImagesGroupController LabRequestImagesGroup
        {
            get
            {
                return LabRequestImagesGroupController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to LabResults controller
        /// </summary>
        public LabResultsController LabResults
        {
            get
            {
                return LabResultsController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to PrescriptionImagesGroup controller
        /// </summary>
        public PrescriptionImagesGroupController PrescriptionImagesGroup
        {
            get
            {
                return PrescriptionImagesGroupController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to MedicalProfile controller
        /// </summary>
        public MedicalProfileController MedicalProfile
        {
            get
            {
                return MedicalProfileController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Lifestyles controller
        /// </summary>
        public LifestylesController Lifestyles
        {
            get
            {
                return LifestylesController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to ChronicDiseases controller
        /// </summary>
        public ChronicDiseasesController ChronicDiseases
        {
            get
            {
                return ChronicDiseasesController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Allergies controller
        /// </summary>
        public AllergiesController Allergies
        {
            get
            {
                return AllergiesController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to IndividualImages controller
        /// </summary>
        public IndividualImagesController IndividualImages
        {
            get
            {
                return IndividualImagesController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Surgeries controller
        /// </summary>
        public SurgeriesController Surgeries
        {
            get
            {
                return SurgeriesController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to MeasurementsRevampV5 controller
        /// </summary>
        public MeasurementsRevampV5Controller MeasurementsRevampV5
        {
            get
            {
                return MeasurementsRevampV5Controller.Instance;
            }
        }

        /// <summary>
        /// Singleton access to ReservationRequests controller
        /// </summary>
        public ReservationRequestsController ReservationRequests
        {
            get
            {
                return ReservationRequestsController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to NewsFeed controller
        /// </summary>
        public NewsFeedController NewsFeed
        {
            get
            {
                return NewsFeedController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Events controller
        /// </summary>
        public EventsController Events
        {
            get
            {
                return EventsController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to NearbyLocations controller
        /// </summary>
        public NearbyLocationsController NearbyLocations
        {
            get
            {
                return NearbyLocationsController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Appointments controller
        /// </summary>
        public AppointmentsController Appointments
        {
            get
            {
                return AppointmentsController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Session controller
        /// </summary>
        public SessionController Session
        {
            get
            {
                return SessionController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to LabRequests controller
        /// </summary>
        public LabRequestsController LabRequests
        {
            get
            {
                return LabRequestsController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Drugs controller
        /// </summary>
        public DrugsController Drugs
        {
            get
            {
                return DrugsController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Places controller
        /// </summary>
        public PlacesController Places
        {
            get
            {
                return PlacesController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Doctors controller
        /// </summary>
        public DoctorsController Doctors
        {
            get
            {
                return DoctorsController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to CrossBorderTreatments controller
        /// </summary>
        public CrossBorderTreatmentsController CrossBorderTreatments
        {
            get
            {
                return CrossBorderTreatmentsController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Comments controller
        /// </summary>
        public CommentsController Comments
        {
            get
            {
                return CommentsController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Paypal controller
        /// </summary>
        public PaypalController Paypal
        {
            get
            {
                return PaypalController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to DicomMREs controller
        /// </summary>
        public DicomMREsController DicomMREs
        {
            get
            {
                return DicomMREsController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to VideoRequests controller
        /// </summary>
        public VideoRequestsController VideoRequests
        {
            get
            {
                return VideoRequestsController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to PrescriptionImages controller
        /// </summary>
        public PrescriptionImagesController PrescriptionImages
        {
            get
            {
                return PrescriptionImagesController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Likes controller
        /// </summary>
        public LikesController Likes
        {
            get
            {
                return LikesController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to VideoExtension controller
        /// </summary>
        public VideoExtensionController VideoExtension
        {
            get
            {
                return VideoExtensionController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to EditProfile controller
        /// </summary>
        public EditProfileController EditProfile
        {
            get
            {
                return EditProfileController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Advertisements controller
        /// </summary>
        public AdvertisementsController Advertisements
        {
            get
            {
                return AdvertisementsController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to ResetPassword controller
        /// </summary>
        public ResetPasswordController ResetPassword
        {
            get
            {
                return ResetPasswordController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Messages controller
        /// </summary>
        public MessagesController Messages
        {
            get
            {
                return MessagesController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to LabRequestImages controller
        /// </summary>
        public LabRequestImagesController LabRequestImages
        {
            get
            {
                return LabRequestImagesController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Measurements controller
        /// </summary>
        public MeasurementsController Measurements
        {
            get
            {
                return MeasurementsController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Confirmation controller
        /// </summary>
        public ConfirmationController Confirmation
        {
            get
            {
                return ConfirmationController.Instance;
            }
        }
        /// <summary>
        /// The shared http client to use for all API calls
        /// </summary>
        public IHttpClient SharedHttpClient
        {
            get
            {
                return BaseController.ClientInstance;
            }
            set
            {
                BaseController.ClientInstance = value;
            }        
        }
        #region Constructors
        /// <summary>
        /// Default constructor
        /// </summary>
        public BalsameeAPIsClient() { }
        #endregion
    }
}