/*
 * BalsameeAPIs.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using BalsameeAPIs.Standard;
using BalsameeAPIs.Standard.Utilities;


namespace BalsameeAPIs.Standard.Models
{
    public class DicomImage : BaseModel 
    {
        // These fields hold the values for the public properties.
        private bool imageFlag;
        private string description;
        private string imageUploadDate;
        private string url;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("image_flag")]
        public bool ImageFlag 
        { 
            get 
            {
                return this.imageFlag; 
            } 
            set 
            {
                this.imageFlag = value;
                onPropertyChanged("ImageFlag");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("description")]
        public string Description 
        { 
            get 
            {
                return this.description; 
            } 
            set 
            {
                this.description = value;
                onPropertyChanged("Description");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("image_upload_date")]
        public string ImageUploadDate 
        { 
            get 
            {
                return this.imageUploadDate; 
            } 
            set 
            {
                this.imageUploadDate = value;
                onPropertyChanged("ImageUploadDate");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("url")]
        public string Url 
        { 
            get 
            {
                return this.url; 
            } 
            set 
            {
                this.url = value;
                onPropertyChanged("Url");
            }
        }
    }
} 