/*
 * BalsameeAPIs.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using BalsameeAPIs.Standard;
using BalsameeAPIs.Standard.Utilities;


namespace BalsameeAPIs.Standard.Models
{
    public class Individual2 : BaseModel 
    {
        // These fields hold the values for the public properties.
        private int id;
        private string birthDate;
        private string gender;
        private string bloodGroup;
        private string relationshipStatus;
        private string childrenNumber;
        private string notes;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("id")]
        public int Id 
        { 
            get 
            {
                return this.id; 
            } 
            set 
            {
                this.id = value;
                onPropertyChanged("Id");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("birth_date")]
        public string BirthDate 
        { 
            get 
            {
                return this.birthDate; 
            } 
            set 
            {
                this.birthDate = value;
                onPropertyChanged("BirthDate");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("gender")]
        public string Gender 
        { 
            get 
            {
                return this.gender; 
            } 
            set 
            {
                this.gender = value;
                onPropertyChanged("Gender");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("blood_group")]
        public string BloodGroup 
        { 
            get 
            {
                return this.bloodGroup; 
            } 
            set 
            {
                this.bloodGroup = value;
                onPropertyChanged("BloodGroup");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("relationship_status")]
        public string RelationshipStatus 
        { 
            get 
            {
                return this.relationshipStatus; 
            } 
            set 
            {
                this.relationshipStatus = value;
                onPropertyChanged("RelationshipStatus");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("children_number")]
        public string ChildrenNumber 
        { 
            get 
            {
                return this.childrenNumber; 
            } 
            set 
            {
                this.childrenNumber = value;
                onPropertyChanged("ChildrenNumber");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("notes")]
        public string Notes 
        { 
            get 
            {
                return this.notes; 
            } 
            set 
            {
                this.notes = value;
                onPropertyChanged("Notes");
            }
        }
    }
} 