/*
 * BalsameeAPIs.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using BalsameeAPIs.Standard;
using BalsameeAPIs.Standard.Utilities;


namespace BalsameeAPIs.Standard.Models
{
    public class ListPrescriptionsgroupsundercertainclinicvisit : BaseModel 
    {
        // These fields hold the values for the public properties.
        private List<string> prescriptions;
        private List<Models.PrescriptionImagesGroup> prescriptionImagesGroups;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("prescriptions")]
        public List<string> Prescriptions 
        { 
            get 
            {
                return this.prescriptions; 
            } 
            set 
            {
                this.prescriptions = value;
                onPropertyChanged("Prescriptions");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("prescription_images_groups")]
        public List<Models.PrescriptionImagesGroup> PrescriptionImagesGroups 
        { 
            get 
            {
                return this.prescriptionImagesGroups; 
            } 
            set 
            {
                this.prescriptionImagesGroups = value;
                onPropertyChanged("PrescriptionImagesGroups");
            }
        }
    }
} 