/*
 * BalsameeAPIs.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using BalsameeAPIs.Standard;
using BalsameeAPIs.Standard.Utilities;


namespace BalsameeAPIs.Standard.Models
{
    public class Meta : BaseModel 
    {
        // These fields hold the values for the public properties.
        private int totalPages;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("total_pages")]
        public int TotalPages 
        { 
            get 
            {
                return this.totalPages; 
            } 
            set 
            {
                this.totalPages = value;
                onPropertyChanged("TotalPages");
            }
        }
    }
} 