/*
 * BalsameeAPIs.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using BalsameeAPIs.Standard;
using BalsameeAPIs.Standard.Utilities;


namespace BalsameeAPIs.Standard.Models
{
    public class Mre : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string id;
        private int createdAt;
        private List<Models.MreComment> mreComments;
        private List<Models.DicomImage> dicomImages;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("id")]
        public string Id 
        { 
            get 
            {
                return this.id; 
            } 
            set 
            {
                this.id = value;
                onPropertyChanged("Id");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("created_at")]
        public int CreatedAt 
        { 
            get 
            {
                return this.createdAt; 
            } 
            set 
            {
                this.createdAt = value;
                onPropertyChanged("CreatedAt");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("mre_comments")]
        public List<Models.MreComment> MreComments 
        { 
            get 
            {
                return this.mreComments; 
            } 
            set 
            {
                this.mreComments = value;
                onPropertyChanged("MreComments");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("dicom_images")]
        public List<Models.DicomImage> DicomImages 
        { 
            get 
            {
                return this.dicomImages; 
            } 
            set 
            {
                this.dicomImages = value;
                onPropertyChanged("DicomImages");
            }
        }
    }
} 