/*
 * BalsameeAPIs.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using BalsameeAPIs.Standard;
using BalsameeAPIs.Standard.Utilities;


namespace BalsameeAPIs.Standard.Models
{
    public class MreComment : BaseModel 
    {
        // These fields hold the values for the public properties.
        private int commentId;
        private string body;
        private int createdAt;
        private int updatedAt;
        private Models.Individual3 individual;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("comment_id")]
        public int CommentId 
        { 
            get 
            {
                return this.commentId; 
            } 
            set 
            {
                this.commentId = value;
                onPropertyChanged("CommentId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("body")]
        public string Body 
        { 
            get 
            {
                return this.body; 
            } 
            set 
            {
                this.body = value;
                onPropertyChanged("Body");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("created_at")]
        public int CreatedAt 
        { 
            get 
            {
                return this.createdAt; 
            } 
            set 
            {
                this.createdAt = value;
                onPropertyChanged("CreatedAt");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("updated_at")]
        public int UpdatedAt 
        { 
            get 
            {
                return this.updatedAt; 
            } 
            set 
            {
                this.updatedAt = value;
                onPropertyChanged("UpdatedAt");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("individual")]
        public Models.Individual3 Individual 
        { 
            get 
            {
                return this.individual; 
            } 
            set 
            {
                this.individual = value;
                onPropertyChanged("Individual");
            }
        }
    }
} 