/*
 * BalsameeAPIs.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using BalsameeAPIs.Standard;
using BalsameeAPIs.Standard.Utilities;


namespace BalsameeAPIs.Standard.Models
{
    public class News : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string id;
        private string cover;
        private string title;
        private string contentBrief;
        private string createdAt;
        private int viewsCount;
        private int likesCount;
        private int commentsCount;
        private bool isLiked;
        private string savedLinkId;
        private int shareCount;
        private Models.SpecialTag specialTag;
        private Models.NewsSource newsSource;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("id")]
        public string Id 
        { 
            get 
            {
                return this.id; 
            } 
            set 
            {
                this.id = value;
                onPropertyChanged("Id");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("cover")]
        public string Cover 
        { 
            get 
            {
                return this.cover; 
            } 
            set 
            {
                this.cover = value;
                onPropertyChanged("Cover");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("title")]
        public string Title 
        { 
            get 
            {
                return this.title; 
            } 
            set 
            {
                this.title = value;
                onPropertyChanged("Title");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("content_brief")]
        public string ContentBrief 
        { 
            get 
            {
                return this.contentBrief; 
            } 
            set 
            {
                this.contentBrief = value;
                onPropertyChanged("ContentBrief");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("created_at")]
        public string CreatedAt 
        { 
            get 
            {
                return this.createdAt; 
            } 
            set 
            {
                this.createdAt = value;
                onPropertyChanged("CreatedAt");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("views_count")]
        public int ViewsCount 
        { 
            get 
            {
                return this.viewsCount; 
            } 
            set 
            {
                this.viewsCount = value;
                onPropertyChanged("ViewsCount");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("likes_count")]
        public int LikesCount 
        { 
            get 
            {
                return this.likesCount; 
            } 
            set 
            {
                this.likesCount = value;
                onPropertyChanged("LikesCount");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("comments_count")]
        public int CommentsCount 
        { 
            get 
            {
                return this.commentsCount; 
            } 
            set 
            {
                this.commentsCount = value;
                onPropertyChanged("CommentsCount");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("is_liked")]
        public bool IsLiked 
        { 
            get 
            {
                return this.isLiked; 
            } 
            set 
            {
                this.isLiked = value;
                onPropertyChanged("IsLiked");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("saved_link_id")]
        public string SavedLinkId 
        { 
            get 
            {
                return this.savedLinkId; 
            } 
            set 
            {
                this.savedLinkId = value;
                onPropertyChanged("SavedLinkId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("share_count")]
        public int ShareCount 
        { 
            get 
            {
                return this.shareCount; 
            } 
            set 
            {
                this.shareCount = value;
                onPropertyChanged("ShareCount");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("special_tag")]
        public Models.SpecialTag SpecialTag 
        { 
            get 
            {
                return this.specialTag; 
            } 
            set 
            {
                this.specialTag = value;
                onPropertyChanged("SpecialTag");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("news_source")]
        public Models.NewsSource NewsSource 
        { 
            get 
            {
                return this.newsSource; 
            } 
            set 
            {
                this.newsSource = value;
                onPropertyChanged("NewsSource");
            }
        }
    }
} 