/*
 * BalsameeAPIs.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using BalsameeAPIs.Standard;
using BalsameeAPIs.Standard.Utilities;


namespace BalsameeAPIs.Standard.Models
{
    public class Newssuccess : BaseModel 
    {
        // These fields hold the values for the public properties.
        private List<Models.News> news;
        private Models.Meta meta;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("news")]
        public List<Models.News> News 
        { 
            get 
            {
                return this.news; 
            } 
            set 
            {
                this.news = value;
                onPropertyChanged("News");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("meta")]
        public Models.Meta Meta 
        { 
            get 
            {
                return this.meta; 
            } 
            set 
            {
                this.meta = value;
                onPropertyChanged("Meta");
            }
        }
    }
} 