/*
 * BalsameeAPIs.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using BalsameeAPIs.Standard;
using BalsameeAPIs.Standard.Utilities;


namespace BalsameeAPIs.Standard.Models
{
    public class PrescriptionImagesGroup : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string id;
        private List<Models.PrescriptionImage> prescriptionImages;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("id")]
        public string Id 
        { 
            get 
            {
                return this.id; 
            } 
            set 
            {
                this.id = value;
                onPropertyChanged("Id");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("prescription_images")]
        public List<Models.PrescriptionImage> PrescriptionImages 
        { 
            get 
            {
                return this.prescriptionImages; 
            } 
            set 
            {
                this.prescriptionImages = value;
                onPropertyChanged("PrescriptionImages");
            }
        }
    }
} 