/*
 * BalsameeAPIs.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using BalsameeAPIs.Standard;
using BalsameeAPIs.Standard.Utilities;


namespace BalsameeAPIs.Standard.Models
{
    public class Uploadradiologyrequestimagegroupfile : BaseModel 
    {
        // These fields hold the values for the public properties.
        private int id;
        private List<Models.RadiologyRequestImage> radiologyRequestImage;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("id")]
        public int Id 
        { 
            get 
            {
                return this.id; 
            } 
            set 
            {
                this.id = value;
                onPropertyChanged("Id");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("radiology_request_image")]
        public List<Models.RadiologyRequestImage> RadiologyRequestImage 
        { 
            get 
            {
                return this.radiologyRequestImage; 
            } 
            set 
            {
                this.radiologyRequestImage = value;
                onPropertyChanged("RadiologyRequestImage");
            }
        }
    }
} 